spring.application.name=TaskList

spring.datasource.url=jdbc:postgresql://localhost:5432/tasklist
spring.datasource.username=tasklist
spring.datasource.password=tasklist
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

jwt.secret=qYLkuvrCXmZ4HK0KLJnqZ59lh2fZ6QRCFJ/4Cn1DxpFcLqC/PjhdBEcIGC3f9v7j
jwt.expiration=86400000