spring.application.name=TaskList

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test

jwt.secret=qYLkuvrCXmZ4HK0KLJnqZ59lh2fZ6QRCFJ/4Cn1DxpFcLqC/PjhdBEcIGC3f9v7j
jwt.expiration=86400000